# Generated by Django 4.1.7 on 2023-04-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SLC', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
