# Generated by Django 4.1.7 on 2023-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLC', '0003_lista_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(default='Sem itens')),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='items',
            field=models.ManyToManyField(to='SLC.itens'),
        ),
    ]
